services:
  openroute-mcp:
    build: .
    restart: unless-stopped
    # environment:
    #   - VIRTUAL_HOST=openroute-mcp.vemonet.mooo.com
    #   - LETSENCRYPT_HOST=openroute-mcp.vemonet.mooo.com
    ports:
      - 8888:8888
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./src:/app/src
